# Generated by Django 6.0 on 2026-07-01 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_at', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(default=50)),
                ('status', models.CharField(choices=[('schedule', 'Agendamento'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Realizado'), ('missed', 'Faltou')], default='schedule', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
        ),
    ]
