# Generated by Django 6.0 on 2026-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule_at',
            field=models.DateTimeField(),
        ),
    ]
