# Generated by Django 6.0 on 2026-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('completed', 'Realizado'), ('no_show', 'Faltou')], default='scheduled', max_length=20),
        ),
    ]
