# Generated by Django 6.0 on 2026-07-01 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_appointment_schedule_at'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('summary', models.TextField()),
                ('evolution_notes', models.TextField(blank=True, null=True)),
                ('patient_mood', models.CharField(blank=True, choices=[('very_bad', 'Muito mal'), ('bad', 'Mal'), ('neutral', 'Neutro'), ('good', 'Bem'), ('very_good', 'Muito bem')], max_length=20, null=True)),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_session', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_sessions', to='patients.patient')),
            ],
        ),
    ]
