# Generated by Django 6.0 on 2026-07-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapysession',
            name='homework',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='session_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='therapysession',
            name='summary',
            field=models.TextField(help_text='Resumo da sessão'),
        ),
    ]
